### ISSUE TITLE
Azure web app integration

### ISSUE THREAD

**Issue by kgruszka** [cludden/mycro#26]
I used yeoman to generate basic mycro app and all is working locally. The problem appears when I deploy the app to azure web app service. Deploy is successfulI. I think it's something with the server configuration since it is not available through binded dns - zero response. My web.config is pointing to index.js to indicate iisnode module main file and I have 'process.env.PORT' in my server config file (server.js).

config/server.js
`'use strict';

module.exports = {
    port: process.env.PORT || 8080,
    middleware: [
        'acceptParser',
        'dateParser',
        'queryParser',
        'bodyParser',
        'morgan',
        'request',
        'request-all-params'
    ]
};`

**Comment by cludden** [comment]
Hey @kgruszka, I'm not too familiar with Azure web apps or deploying node on windows, i'll try to look into it today and see what I can find. A couple questions I have:
- Are there any log files available to you with Azure Web Apps? 
- What node version are you using in locally/production?
- What operating system are you using locally?

**Comment by kgruszka** [comment]
Hi.
Azure is using iisnode (https://github.com/tjanczuk/iisnode) internally for hosting nodejs apps. Web apps are running in sandboxes (https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox). It casues some limitations. With iisnode you have to get the port value for server.listen(port) from process.env.PORT so I did it as mentioned in the first post. Locally I'm not using iisnode so I cannot test it. OS is Windows 10 x64 but it works well with Ubuntu 14.04 too. Node version 4.2.3. I think it can be some issue with hosting it through iisnode. There are a lot of logs but I found something that may indicate the problem.
[app_logs.txt](https://github.com/cludden/mycro/files/180093/app_logs.txt)
process.env.PORT is correct way of accessing the port value but it looks as the server is not binding to that port

**[EDIT]**:
I inserted a line of code to log the port and here is the result.
[app_logs2.txt](https://github.com/cludden/mycro/files/180111/app_logs2.txt)
[app.js.txt](https://github.com/cludden/mycro/files/180116/app.js.txt)

**Comment by kgruszka** [comment]
Finally, I had some time today to read the code. It was quick fix. With iisnode the port value may not be a number... I tested it and the web app responds ;)
I've created a  pull request ^^

**Comment by cludden** [comment]
Awesome, glad you were able to figure it out. Thanks for the contribution!

**Comment by kgruszka** [comment]
Glad to be helpful ;) 
When can I expect new release? We want to use this library in our project and be able to install it via npm.

**Comment by cludden** [comment]
just published 0.3.3

**Comment by kgruszka** [comment]
Sorry for the mess. I omitted the line above that was parsing port value to int. In case of string it results in NaN what causes error on Azure... I've just created pull request with fix for that.

**Comment by kgruszka** [comment]
All is working perfectly now. Thanks a lot ;)
